services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:cached  # Mode cached pour meilleures performances
      - /var/www/html/var/cache  # Exclusion du cache Symfony
      - /var/www/html/vendor     # Exclusion du dossier vendor
    deploy:
      resources:
        limits:
          cpus: '2'    # Allocation de 2 CPUs
          memory: 1G   # Allocation de 1GB RAM
    depends_on:
      database:
        condition: service_healthy
      mercure:
        condition: service_started
    environment:
      DATABASE_URL: "mysql://root:@database:3306/symlivredb?serverVersion=mariadb-10.4.32&charset=utf8mb4"
      MERCURE_URL: "http://mercure/.well-known/mercure"
      MERCURE_PUBLIC_URL: "http://localhost:3000/.well-known/mercure"
      MERCURE_JWT_SECRET: "${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}"
      # Ajoutez ces variables pour optimiser PHP
      PHP_OPCACHE_ENABLE: '1'
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: '0'  # Désactive en prod (mais gardez en dev)
      APP_ENV: dev  # Force l'environnement de développement

  web:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  database:
    image: mariadb:10.4.32
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: symlivredb
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    ports:
      - "3000:3000"

  mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data: